---
name: FOSS Contribution Request
description: "Request to contribute to an open source project following the company FOSS contribution policy."
title: "[FOSS Contribution] <Short description of the change>"
labels:
  - "foss"
  - "contribution-request"
assignees:
  - "your-org-foss-responsible"

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Project Information
        Please fill out the following information about the project and your intended contribution.

  - type: input
    id: project-name
    attributes:
      label: "Project Name"
      description: "Please provide the name of the open-source project you want to contribute to."
      placeholder: "e.g. AwesomeProject"


  - type: input
    id: internal-repo
    attributes:
      label: " internal repository for development and quality checks (e.g. GitHub Enterprise)"
      description: "Please provide the URL of the internal repository used for development and quality assurance, typically hosted on a platform like GitHub Enterprise."
      placeholder: "e.g. https://github.company.com/org/project-repo"

  - type: input
    id: project-url
    attributes:
      label: "Project URL"
      description: " Please provide the GitHub URL of the repository you want to contribute to."
      placeholder: "e.g. https://github.com/user/repository"

  - type: input
    id: target-org
    attributes:
      label: "GitHub Organization (Personal or Corporate)"
      description: "In which GitHub organization will the fork live and where will you contribute from?"
      placeholder: "e.g. your-org, your-username"

  - type: input
    id: target-repo
    attributes:
      label: "User ID"
      description: "Please enter the contributor’s user identifier."
      placeholder: "e.g. user_9283"

 - type: markdown
  attributes:
    value: |
      ### Strategic FOSS Platform

      Please make sure you are contributing on an [approved platform](https://fosswik-confluence.dot.app.corpintra.net/display/0064/CONTRIBUTE+Open+Source).

      
  - type: markdown
    attributes:
      value: |
        ## ✅ Contributor Requirements
        Please confirm the contributor meets all requirements for contributing.

 - type: dropdown
    id: license
    attributes:
      label: "Choose a License"
      description: "Select the license that applies to this project"
      required: true
      options: 
      - AES256 License
- AMSFonts license
- ANTLR Software Rights Notice
- ANTLR Software Rights Notice with license fallback
- Academic Free License v1.1
- Academic Free License v1.2
- Academic Free License v2.0
- Academic Free License v2.1
- Academic Free License v3.0
- Academy of Motion Picture Arts and Sciences BSD
- AdaCore Doc License
- Adobe Glyph List License
- Adobe Helvetica License
- Adobe Systems Open Source Agreement
- Adobe Utopia License
- Advanced Micro Devices License - 1989
- Aelfred2 License
- Afmparse License
- Apache License 1.0
- Apache License 1.1
- Apache License 2.0
- Apple Public Source License 1.2
- Apple Public Source License 2.0
- Apple iOS Sample Code License
- Arc4 Random Number Generator License
- Arphic Public License
- Artistic License 1.0
- Artistic License 1.0 (Perl)
- Artistic License 2.0
- Avisynth C Interface Exception to GPL-2.0-or-later
- Ayam License
- BSD 2-Clause "Simplified" License
- BSD 2-Clause - Ian Darwin variant
- BSD 2-Clause FreeBSD License
- BSD 2-Clause NetBSD License
- BSD 2-Clause with views sentence
- BSD 3-Clause "New" or "Revised" License
- BSD 3-Clause Clear License
- BSD 3-Clause No Nuclear License
- BSD 3-Clause acpica variant
- BSD 3-Clause with Google-XGB Patent License
- BSD 4 Clause Shortened
- BSD 4-Clause "Original" or "Old" License
- BSD 4.3 RENO License
- BSD 4.3 TAHOE License
- BSD Advertising Acknowledgement License
- BSD Protection License
- BSD Simplified with Unchanged requirement
- BSD Source Code Attribution
- BSD Source Code Attribution - beginning of file variant
- BSD Zero Clause License
- BSD with Attribution and HPND disclaimer
- BSD-2-Clause Mike Matsnev License
- BSD-2-Clause Plus Patent License
- BSD-3-Clause X11 disclaimer
- BSD-3-Clause tcpdump variant
- BSD-4-Clause (University of California-Specific)
- BSD-Simplified Intel
- BSDTar
- Beerware License
- BigInteger License
- Bitstream Vera Font License
- Blue Oak Model License 1.0.0
- Boost Software License 1.0
- Brian Gladman 2-Clause License
- Brian Gladman License
- CMU Mach - no notices-in-documentation variant
- CMU License
- CMU Mach License
- CNRI Python License
- CNRI Python Open Source GPL Compatible License Agreement
- Caldera License (without preamble)
- Carnegie Mellon License
- Carnegie Mellon Simple License
- Carnegie Mellon UC Regents MIT-style License
- Castor License
- Catharon License
- CeCILL Free Software License Agreement v2.0
- Clarified Artistic License
- Clips License
- Code Project Open License 1.02
- Common Development and Distribution License 1.0
- Common Development and Distribution License 1.1
- Common Public Attribution License 1.0
- Common Public License 1.0
- Creative Commons Attribution 1.0 Generic
- Creative Commons Attribution 2.5 Generic
- Creative Commons Attribution 3.0 Austria
- Creative Commons Attribution 3.0 New Zealand
- Creative Commons Attribution 3.0 Unported
- Creative Commons Attribution 4.0 International
- Creative Commons Attribution Share Alike 2.0 Generic
- Creative Commons Attribution Share Alike 3.0 Unported
- Creative Commons Attribution Share Alike 4.0 International
- Creative Commons Public Domain Dedication and Certification
- Creative Commons Zero v1.0 Universal
- CrpytoSwift
- Cup Parser Generator License
- Cygnus License
- DOC License
- David M. Gay dtoa License
- Diffstat License
- Do What The F*ck You Want To Public License
- Eclipse Distribution License v1.0
- Eclipse Public License 1.0
- Eclipse Public License 2.0
- Educational Community License v2.0
- Enlightenment License (e16)
- European Union Public License 1.0
- European Union Public License 1.1
- European Union Public License 1.2
- FFTPACK License
- FSF All Permissive License (without Warranty)
- FSF Unlimited License
- FSF Unlimited License (With License Retention and Warranty Disclaimer)
- Facebook Patent Grant v2
- FatFs License
- FatFs Module License
- Festival Speech Synthesis System License
- Flavor Artistic License
- Flora v1.1 License
- Fraunhofer FDK AAC Codec Library
- FreeImage Public License v1.0
- FreeRTOS License
- Freely Distributable LIBM License
- Freescale Semiconductor License
- Freetype Project License
- Freetype Project License with Freetype Patent Grant
- Frontier Artistic License
- GD License
- GNU Affero General Public License v3.0
- GNU Affero General Public License v3.0 only
- GNU Affero General Public License v3.0 or later
- GNU Free Documentation License v1.1
- GNU Free Documentation License v1.2
- GNU Free Documentation License v1.3
- GNU Free Documentation License v1.3 only
- GNU General Public License v1.0 only
- GNU General Public License v1.0 or later
- GNU General Public License v1.0 or later
- GNU General Public License v2.0 only
- GNU General Public License v2.0 only
- GNU General Public License v2.0 or later
- GNU General Public License v2.0 or later
- GNU General Public License v2.0 or later w/Autoconf exception
- GNU General Public License v2.0 or later w/GNAT exception
- GNU General Public License v2.0 w/Autoconf exception
- GNU General Public License v2.0 w/Bison exception
- GNU General Public License v2.0 w/Classpath exception
- GNU General Public License v2.0 w/GCC Runtime Library exception
- GNU General Public License v2.0 with Libtool exception
- GNU General Public License v2.0 with Linux Syscall Note
- GNU General Public License v2.0 with the Universal FOSS Exception, Version 1.0
- GNU General Public License v3.0 only
- GNU General Public License v3.0 only
- GNU General Public License v3.0 or later
- GNU General Public License v3.0 or later
- GNU General Public License v3.0 or later w/Autoconf exception
- GNU General Public License v3.0 w/GCC Runtime Library exception
- GNU General Public License v3.0 with Bison exception 2.2
- GNU Lesser General Public License v2.1 only
- GNU Lesser General Public License v2.1 only
- GNU Lesser General Public License v2.1 or later
- GNU Lesser General Public License v2.1 or later
- GNU Lesser General Public License v3.0 only
- GNU Lesser General Public License v3.0 only
- GNU Lesser General Public License v3.0 or later
- GNU Lesser General Public License v3.0 or later
- GNU Library General Public License v2 only
- GNU Library General Public License v2 only
- GNU Library General Public License v2 or later
- GNU Library General Public License v2 or later
- Gary S. Brown License
- Generic XTS License
- Go BSD 3-Clause with Patent License
- Google Patent License for Go
- Google Patent License for WebM
- Google Patent License for WebRTC
- HPND with US Government export control warning and modification rqmt
- Historical Permission Notice and Disclaimer
- Historical Permission Notice and Disclaimer - INRIA-IMAG variant
- Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant
- Historical Permission Notice and Disclaimer - Kevlin Henney variant
- Historical Permission Notice and Disclaimer - Markus Kuhn variant
- Historical Permission Notice and Disclaimer - Pbmplus variant
- Historical Permission Notice and Disclaimer - sell variant
- Historical Permission Notice and Disclaimer with MIT disclaimer
- IBM DHCP License
- IBM Public License v1.0
- ICU License
- ICU License 58 and later
- INEGI's TERMS OF FREE USE OF INFORMATION
- INPOLY License
- ISC License
- ISC Veillard variant
- ITU-T General Public License
- ImageMagick License
- Independent JPEG Group License
- Independent JPEG Group License - short
- Independent JPEG Group License 2020
- Indiana University Extreme! Lab Software License 1.2
- Indiana University Extreme! Lab Software License Version 1.1.1
- Info-ZIP License
- JSON License
- JTidy
- Jasper Arev Fonts License
- Jdom License
- Jython License 2.0
- KSH License
- Kalle Kaukonen License
- Kaz Free Software License
- Kazlib License
- Kerberos License
- LGPL Version 3.0 with libfreefare exception
- LGPL-2.1-or-later WITH Libtool-exception
- LGPL-2.1-or-later WITH cryptsetup-OpenSSL-exception
- LLVM Exception to Apache-2.0
- LLVM Release License
- LPD Documentation License
- Legion of the Bouncy Castle License
- Libmng License
- Los Alamos National Laboratory License
- MATPLOTLIB License 1.3.0 or Later
- MIT Cheusov variant
- MIT License
- MIT License 1998
- MIT License Modern Variant
- MIT No Attribution
- MIT Old Style
- MIT Old Style with Legal Disclaimer
- MIT OldStyle No Advertisement License
- MIT Public Domain License
- MIT with Attribution
- MIT with Biorad Disclaimer
- MIT with Legal and Advertising restrictions
- MPL-1.0
- MPL-1.1
- MPL-2.0
- MPL-2.0 or later
- Multics License
- NCSA Open Source License
- NetBSD License
- Open Software License 3.0
- OpenSSL License
- OpenSSL License - Older than 2008
- PostgreSQL License
- Python Software Foundation License 2.0
- RealNetworks Public License
- RecordMinder License
- Ruby License
- Ruby 2.0 License
- RYerson Labs License
- Sather Public License
- SGI Free Software License B
- SGI Free Software License B (free software group use only)
- SIL Open Font License 1.0
- SIL Open Font License 1.1
- SNIA License
- Software License of the Standard Template Library (STL)
- Stanford University Free Software License
- STDF file format License
- Sun Microsystems Free Software License
- Sun Microsystems License (with restrictions)
- Standard MIT
- The Unlicense
- The Zlib/libpng License
- Unlicense
- Unicode Software License
- University of Illinois/NCSA Open Source License
- University of Illinois/NCSA Open Source License 3.0
- VexWare License
- W3C Software Notice and License
- W3C Software License (general)
- W3C XML Signature Syntax and Processing Specification
- X11 License
- zlib License



  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Qualification & Legal Checklist"
      options:
        - label: "The contributor holds a valid **FOSS Driver’s License Certification**"
        - label: "Contributor has been **nominated** to contribute FOSS"
      
        - label: "Contributor is [onboarded](https://fosswik-confluence.dot.app.corpintra.net/display/0064/Onboarding) into Contribution platform "
        - label: "Rights to contribute the code are **clearly owned** by the company"
        - label: "No license conflicts or IP risks (license scan complete)"
        - label: "Peer code review has been completed"
        - label: "Code contains no personal data, trademarks, or confidential information"
        - label: "Contribution includes correct legal notice and uses ['on-behalf-of'](https://fosswik-confluence.dot.app.corpintra.net/pages/viewpage.action?pageId=21314791) if applicable"

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes / Legal Questions"
      placeholder: "Optional: Any open questions, legal concerns, or special requirements."

  - type: markdown
    attributes:
      value: |
        ## 📩 Submission
        Once submitted, your request will be reviewed by the responsible FOSS team. Please ensure all checkboxes are completed and information is accurate.
