name: FOSS Contribution Request
description: "Request to contribute to an open source project following the company FOSS contribution policy."
title: "[FOSS Contribution] <Short description of the change>"
labels:
  - "foss"
  - "contribution-request"
assignees:
  - "your-org-foss-responsible"

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Project Information
        Please fill out the following information about the project and your intended contribution.

  - type: input
    id: project-name
    attributes:
      label: "Project Name"
      description: "Please provide the name of the open-source project you want to contribute to."
      placeholder: "e.g. AwesomeProject"

  - type: input
    id: internal-repo
    attributes:
      label: "Internal repository for development and quality checks (e.g. GitHub Enterprise)"
      description: "Please provide the URL of the internal repository used for development and quality assurance, typically hosted on a platform like GitHub Enterprise."
      placeholder: "e.g. https://github.company.com/org/project-repo"

  - type: input
    id: project-url
    attributes:
      label: "Project URL"
      description: "Please provide the GitHub URL of the repository you want to contribute to."
      placeholder: "e.g. https://github.com/user/repository"

  - type: input
    id: target-org
    attributes:
      label: "GitHub Organization (Personal or Corporate)"
      description: "In which GitHub organization will the fork live and where will you contribute from?"
      placeholder: "e.g. https://github.com/yourusername or https://github.com/yourorganization"

  - type: input
    id: target-repo
    attributes:
      label: "User ID"
      description: "Please enter the contributor’s user identifier."
      placeholder: "e.g. user_9283"

  - type: markdown
    attributes:
      value: |
        ### Strategic FOSS Platform
        Please make sure you are contributing on an [approved platform](https://fosswik-confluence.dot.app.corpintra.net/display/0064/CONTRIBUTE+Open+Source).

  - type: input
    id: license
    attributes:
      label: "License ID"
      description: "Please enter the license ID (e.g., Apache-2.0, MIT). You can find the full list here: [License Overview](https://disco.app.corpintra.net/#/dashboard/licenses)"
      placeholder: "e.g., Apache-2.0"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ Contributor Requirements
        Please confirm the contributor meets all requirements for contributing.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Qualification & Legal Checklist"
      options:
        - label: "The contributor holds a valid **FOSS Driver’s License Certification**"
        - label: "Contributor has been **nominated** to contribute FOSS"
        - label: "Contributor is [onboarded](https://fosswik-confluence.dot.app.corpintra.net/display/0064/Onboarding) into Contribution platform"
        - label: "Rights to contribute the code are **clearly owned** by the company"
        - label: "No license conflicts or IP risks (license scan complete)"
        - label: "Peer code review has been completed"
        - label: "Code contains no personal data, trademarks, or confidential information"
        - label: "Contribution includes correct legal notice and uses ['on-behalf-of'](https://fosswik-confluence.dot.app.corpintra.net/pages/viewpage.action?pageId=21314791) if applicable"

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes / Legal Questions"
      placeholder: "Optional: Any open questions, legal concerns, or special requirements."

  - type: markdown
    attributes:
      value: |
        ## 📩 Submission
        Once submitted, your request will be reviewed by the responsible FOSS team. Please ensure all checkboxes are completed and information is accurate.
