---
name: FOSS Contribution Request
description: "Request to contribute to an open source project following the company FOSS contribution policy."
title: "[FOSS Contribution] <Short description of the change>"
labels:
  - "foss"
  - "contribution-request"
assignees:
  - "your-org-foss-responsible"

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Project Information
        Please fill out the following information about the project and your intended contribution.

  - type: input
    id: project-name
    attributes:
      label: "Project Name"
      description: "Please provide the name of the open-source project you want to contribute to."
      placeholder: "e.g. AwesomeProject"

  - type: input
    id: project-url
    attributes:
      label: "Project URL"
      description: " Please provide the GitHub URL of the repository you want to contribute to."
      placeholder: "e.g. https://github.com/user/repository"

  - type: input
    id: target-org
    attributes:
      label: "GitHub Organization (Personal or Corporate)"
      description: "In which GitHub organization will the fork live and where will you contribute from?"
      placeholder: "e.g. your-org, your-username"

  - type: input
    id: target-repo
    attributes:
      label: "User ID"
      description: "Enter the contributor’s user identifier."
      placeholder: "e.g. user_9283"

  - type: dropdown
    id: foss-platform
    attributes:
      label: "Strategic FOSS Platform"
      description: "Select the platform you are contributing on"
      options:
        - "GitHub (approved)"
        - "GitLab (approved)"
        - "Other (requires approval)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ Contributor Requirements
        Please confirm the contributor meets all requirements for contributing.

  - type: dropdown
    id: foss-license
    attributes:
      label: "FOSS License used"
      options:
        - "Apache 2.0"
        - "MIT"
        - "GPL"
        - "Other"
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Qualification & Legal Checklist"
      options:
        - label: "The contributor holds a valid **FOSS Driver’s License Certification**"
        - label: "Contributor has been **nominated** to contribute FOSS"
      
        - label: "Contributor is onboarded into Contribution platform"
        - label: "Rights to contribute the code are **clearly owned** by the company"
        - label: "No license conflicts or IP risks (license scan complete)"
        - label: "Peer code review has been completed"
        - label: "Code contains no personal data, trademarks, or confidential information"
        - label: "Contribution includes correct legal notice and uses ['on-behalf-of'](https......) if applicable"

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes / Legal Questions"
      placeholder: "Optional: Any open questions, legal concerns, or special requirements."

  - type: markdown
    attributes:
      value: |
        ## 📩 Submission
        Once submitted, your request will be reviewed by the responsible FOSS team. Please ensure all checkboxes are completed and information is accurate.
