name: "📨 Request to Publish"
about: "Use this form to submit a request for publishing content."
title: "[Request] Publish ..."
labels: ["request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Publish Request Form
        Please fill out the following details to request publication.

  - type: input
    id: title
    attributes:
      label: Title
      description: What's the title of the content you'd like to publish?
      placeholder: "My amazing feature"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a short summary of what you're trying to publish.
      placeholder: "This is a new feature that allows users to..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the type of content.
      options:
        - Blog Post
        - Feature Announcement
        - Technical Documentation
        - Other
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: Who's the main author?
      placeholder: "yourname123"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following:
      options:
        - label: I confirm that the content is original and ready to be reviewed.
          required: true
