name: Autofill Project Board
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read
  repository-projects: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Node ID
        id: get-id
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const result = await github.graphql(`
              query($owner: String!, $repo: String!, $issueNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issueNumber) {
                    id
                  }
                }
              }
            `, {
              owner,
              repo,
              issueNumber
            });

            const issueId = result.repository.issue.id;
            core.setOutput("issueId", issueId);

      - name: Add Issue to Project Board
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = "PVT_kwHOCMwB1M4A2ttm"; // Dein Project V2 ID
            const issueId = core.getInput("issueId");

            const result = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId,
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId,
              contentId: issueId
            });

            core.info(`Item added: ${result.addProjectV2ItemById.item.id}`);
