name: Autofill Project Fields from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read
  id-token: write
  pull-requests: read
  projects: write  # ✅ Wichtig: 'projects', nicht 'project'

jobs:
  autofill-project:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/foss-contribution.yml

      - name: Autofill GitHub Project fields
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = "PVT_kwHOCMwB1M4A2ttm"; // Ersetze durch dein echtes ProjectV2 ID
            const issue = context.payload.issue;
            const outputs = {
              "Project Name": "${{ steps.issue-parser.outputs.issueparser_project_name }}",
              "Internal repository": "${{ steps.issue-parser.outputs.issueparser_internal_repository }}",
              "Project URL": "${{ steps.issue-parser.outputs.issueparser_project_url }}",
              "GitHub Organization": "${{ steps.issue-parser.outputs.issueparser_github_organization }}",
              "User ID": "${{ steps.issue-parser.outputs.issueparser_user_id }}",
              "License ID": "${{ steps.issue-parser.outputs.issueparser_license_id }}"
            };

            const headers = {
              "Authorization": `Bearer ${process.env.GITHUB_TOKEN}`,
              "Content-Type": "application/json"
            };

            async function graphql(query, variables = {}) {
              const response = await fetch("https://api.github.com/graphql", {
                method: "POST",
                headers,
                body: JSON.stringify({ query, variables }),
              });
              const result = await response.json();
              if (result.errors) {
                console.error("GraphQL Errors:", result.errors);
                throw new Error("GraphQL query failed");
              }
              return result.data;
            }

            // 1. Felder abrufen
            const fieldQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    fields(first: 50) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;
            const fieldData = await graphql(fieldQuery);
            const fieldMap = {};
            for (const f of fieldData.node.fields.nodes) {
              fieldMap[f.name] = f.id;
            }

            // 2. Issue dem Projekt hinzufügen
            const addItemMutation = `
              mutation {
                addProjectV2ItemById(input: { projectId: "${projectId}", contentId: "${issue.node_id}" }) {
                  item {
                    id
                  }
                }
              }
            `;
            const addItemResult = await graphql(addItemMutation);
            const itemId = addItemResult.addProjectV2ItemById.item.id;

            // 3. Felder automatisch ausfüllen
            for (const [label, value] of Object.entries(outputs)) {
              const fieldId = fieldMap[label];
              if (!fieldId || !value) continue;

              const updateMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "${projectId}",
                    itemId: "${itemId}",
                    fieldId: "${fieldId}",
                    value: { text: "${value}" }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              await graphql(updateMutation);
            }
