name: Add Issue to Project Board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const projectId = "PVT_kwHOCMwB1M4A2ttm";
            const fieldId = "PVTSSF_lAHOCMwB1M4A2ttmzgr-WfQ";
            const optionId = "f75ad846";

            const issueId = context.payload.issue.node_id;

            // Füge das Issue zum Projekt hinzu
            const item = await github.graphql(`
              mutation($projectId:ID!, $contentId:ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId,
              contentId: issueId
            });

            const itemId = item.addProjectV2ItemById.item.id;

            // Setze das Status-Feld auf "New requests"
            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId,
              fieldId,
              optionId
            });
