name: Autofill Project Fields from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read
  id-token: write
  pull-requests: read

jobs:
  autofill-project:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/foss_contribution_request.yml

      - name: Debug parsed outputs
        run: |
          echo "Parsed issue form values:"
          echo "${{ toJSON(steps.issue-parser.outputs) }}"

      - name: Autofill GitHub Project fields
        uses: actions/github-script@v7
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PROJECT_NAME: ${{ steps.issue-parser.outputs.issueparser_project_name }}
          INTERNAL_REPO: ${{ steps.issue-parser.outputs.issueparser_internal_repository_for_development_and_quality_checks_eg_github_enterprise }}
          PROJECT_URL: ${{ steps.issue-parser.outputs.issueparser_project_url }}
          GITHUB_ORG: ${{ steps.issue-parser.outputs.issueparser_github_organisation }}
          USER_ID: ${{ steps.issue-parser.outputs.issueparser_user_id }}
          LICENSE_ID: ${{ steps.issue-parser.outputs.issueparser_license_id }}
        with:
          script: |
            const token = process.env.MY_GITHUB_TOKEN;
            const projectId = "PVT_kwHOCMwB1M4A2ttm";
            const issue = context.payload.issue;

            const outputs = {
              "Project Name": process.env.PROJECT_NAME,
              "Internal repository": process.env.INTERNAL_REPO,
              "Project URL": process.env.PROJECT_URL,
              "GitHub Organisation": process.env.GITHUB_ORG,
              "User ID": process.env.USER_ID,
              "License ID": process.env.LICENSE_ID
            };

            async function graphql(query, variables = {}) {
              const response = await fetch("https://api.github.com/graphql", {
                method: "POST",
                headers: {
                  Authorization: `Bearer ${token}`,
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({ query, variables }),
              });
              const result = await response.json();
              if (result.errors) {
                console.error("GraphQL Errors:", result.errors);
                throw new Error("GraphQL query failed");
              }
              return result.data;
            }

            const fieldQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    fields(first: 50) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;
            const fieldData = await graphql(fieldQuery);
            if (!fieldData?.node) throw new Error("❌ Project ID ungültig oder kein Zugriff");

            const fieldMap = {};
            for (const f of fieldData.node.fields.nodes) {
              fieldMap[f.name] = f.id;
            }

            const addItemMutation = `
              mutation {
                addProjectV2ItemById(input: { projectId: "${projectId}", contentId: "${issue.node_id}" }) {
                  item {
                    id
                  }
                }
              }
            `;
            const addItemResult = await graphql(addItemMutation);
            const itemId = addItemResult.addProjectV2ItemById.item.id;

            for (const [label, value] of Object.entries(outputs)) {
              const fieldId = fieldMap[label];
              if (!fieldId || !value) {
                console.log(`⚠️ Skip field '${label}' (no fieldId or value)`);
                continue;
              }

              const updateMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "${projectId}",
                    itemId: "${itemId}",
                    fieldId: "${fieldId}",
                    value: { text: "${value}" }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              await graphql(updateMutation);
              console.log(`✅ Updated field '${label}' with value '${value}'`);
            }
