name: Autofill Project Fields from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read
  id-token: write
  pull-requests: read

jobs:
  autofill-project:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/foss_contribution_request.yml

      - name: Debug parsed outputs
        run: |
          echo "Project Name: ${{ steps.issue-parser.outputs.issueparser_project-name }}"
          echo "Internal Repository: ${{ steps.issue-parser.outputs.issueparser_internal-repo }}"
          echo "Project URL: ${{ steps.issue-parser.outputs.issueparser_project-url }}"
          echo "GitHub Organization: ${{ steps.issue-parser.outputs.issueparser_target-org }}"
          echo "User ID: ${{ steps.issue-parser.outputs.issueparser_target-repo }}"
          echo "License ID: ${{ steps.issue-parser.outputs.issueparser_license }}"

      - name: Autofill GitHub Project fields
        uses: actions/github-script@v7
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          script: |
            const token = process.env.MY_GITHUB_TOKEN;
            const projectId = "PVT_kwHOCMwB1M4A2ttm";
            const issue = context.payload.issue;

            const outputs = {
              "Project Name": "${{ steps.issue-parser.outputs.issueparser_project-name }}",
              "Internal repository": "${{ steps.issue-parser.outputs.issueparser_internal-repo }}",
              "Project URL": "${{ steps.issue-parser.outputs.issueparser_project-url }}",
              "GitHub Organization": "${{ steps.issue-parser.outputs.issueparser_target-org }}",
              "User ID": "${{ steps.issue-parser.outputs.issueparser_target-repo }}",
              "License ID": "${{ steps.issue-parser.outputs.issueparser_license }}"
            };

            async function graphql(query, variables = {}) {
              const response = await fetch("https://api.github.com/graphql", {
                method: "POST",
                headers: {
                  Authorization: `Bearer ${token}`,
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({ query, variables }),
              });

              const result = await response.json();
              if (result.errors) {
                console.error("GraphQL Errors:", result.errors);
                throw new Error("GraphQL query failed");
              }
              return result.data;
            }

            // 1. Felder des Projekts abfragen
            const fieldQuery = `
              query {
                node(id: "${projectId}") {
                  ... on ProjectV2 {
                    fields(first: 50) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;
            const fieldData = await graphql(fieldQuery);
            if (!fieldData?.node) throw new Error("❌ Project ID ungültig oder kein Zugriff");

            const fieldMap = {};
            for (const f of fieldData.node.fields.nodes) {
              fieldMap[f.name] = f.id;
            }

            // 2. Issue dem Project hinzufügen
            const addItemMutation = `
              mutation {
                addProjectV2ItemById(input: { projectId: "${projectId}", contentId: "${issue.node_id}" }) {
                  item {
                    id
                  }
                }
              }
            `;
            const addItemResult = await graphql(addItemMutation);
            const itemId = addItemResult.addProjectV2ItemById.item.id;

            // 3. Felder befüllen
            for (const [label, value] of Object.entries(outputs)) {
              if (!value || !fieldMap[label]) {
                console.log(`❌ Skip field "${label}" – fehlt oder leer.`);
                continue;
              }

              console.log(`✅ Updating field "${label}" with value: ${value}`);

              const updateMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: "${projectId}",
                    itemId: "${itemId}",
                    fieldId: "${fieldMap[label]}",
                    value: { text: "${value}" }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              await graphql(updateMutation);
            }
