name: Parse FOSS Contribution Issue

on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Parse Issue using github-issue-parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: morabiei/request-to-publish/.github/ISSUE_TEMPLATE/foss-contribution-request.yml

      - name: Show full JSON
        run: echo "$ISSUE_JSON"
        env:
          ISSUE_JSON: ${{ steps.issue-parser.outputs.jsonString }}

      - name: Access specific fields
        run: |
          echo "Project Name: ${{ steps.issue-parser.outputs.issueparser_project-name }}"
          echo "Internal Repository: ${{ steps.issue-parser.outputs.issueparser_internal-repo }}"
          echo "Project URL: ${{ steps.issue-parser.outputs.issueparser_project-url }}"
          echo "GitHub Organization: ${{ steps.issue-parser.outputs.issueparser_target-org }}"
          echo "GitHub Repository: ${{ steps.issue-parser.outputs.issueparser_target-repo }}"
          echo "License ID: ${{ steps.issue-parser.outputs.issueparser_license }}"
          echo "Prerequisites: ${{ steps.issue-parser.outputs.issueparser_prerequisites }}"
          echo "Additional Notes: ${{ steps.issue-parser.outputs.issueparser_notes }}"
